In [50]:
import pandas as pd
import numpy as np

In [51]:
# 加载数据集
df = pd.read_excel(r"D:\GitHubRepos\is6400-business-data-analytics\data\cleaned_dataset.xlsx")
df.head(10)

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005,6,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3.0,192000,6,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000,4,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966,4,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901,4,Automatic,Front,04-May,Left wheel,Silver,4
5,45802912,39493,891,HYUNDAI,Santa FE,2016,Jeep,Yes,Diesel,2.0,160931,4,Automatic,Front,04-May,Left wheel,White,4
6,45656768,1803,761,TOYOTA,Prius,2010,Hatchback,Yes,Hybrid,1.8,258909,4,Automatic,Front,04-May,Left wheel,White,12
7,45816158,549,751,HYUNDAI,Sonata,2013,Sedan,Yes,Petrol,2.4,216118,4,Automatic,Front,04-May,Left wheel,Grey,12
8,45641395,1098,394,TOYOTA,Camry,2014,Sedan,Yes,Hybrid,2.5,398069,4,Automatic,Front,04-May,Left wheel,Black,12
9,45756839,26657,-,LEXUS,RX 350,2007,Jeep,Yes,Petrol,3.5,128500,6,Automatic,4x4,04-May,Left wheel,Silver,12

In [52]:
df.describe()

,ID,Price,Prod. year,Engine volume,Mileage,Cylinders,Airbags
count,1.468100e+04,14681.000000,14681.000000,14681.000000,1.468100e+04,14681.000000,14681.000000
mean,4.558740e+07,17729.341939,2011.563381,2.352762,1.097255e+06,4.634902,6.799264
std,8.888501e+05,17822.538641,4.812077,0.901162,4.133381e+07,1.232426,4.347691
min,2.324298e+07,1.000000,1985.000000,0.000000,0.000000e+00,1.000000,0.000000
25%,4.568933e+07,5372.000000,2010.000000,1.800000,7.285700e+04,4.000000,4.000000
50%,4.577290e+07,14069.000000,2012.000000,2.000000,1.289650e+05,4.000000,6.000000
75%,4.580284e+07,23364.000000,2015.000000,2.500000,1.930000e+05,6.000000,12.000000
max,4.581665e+07,194438.000000,2020.000000,20.000000,2.147484e+09,16.000000,16.000000

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14681 entries, 0 to 14680
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                14681 non-null  int64
 1   Price             14681 non-null  int64
 2   Levy              14681 non-null  object
 3   Manufacturer      14681 non-null  object
 4   Model             14681 non-null  object
 5   Prod. year        14681 non-null  int64
 6   Category          14681 non-null  object
 7   Leather interior  14681 non-null  object
 8   Fuel type         14681 non-null  object
 9   Engine volume     14681 non-null  float64
 10  Mileage           14681 non-null  int64
 11  Cylinders         14681 non-null  int64
 12  Gear box type     14681 non-null  object
 13  Drive wheels      14681 non-null  object
 14  Doors             14681 non-null  object
 15  Wheel             14681 non-null  object
 16  Color             14681 non-null  object
 17  Airbags           14681 non-null  int64
dtypes: float64(1), int64(6), object(11)
memory usage: 2.0+ MB

In [54]:
def preprocess_data(df):
    # 处理Levy列
    df['Levy'] = df['Levy'].replace('-', np.nan).astype(float)
    
    # 处理Doors列：提取有效数字并转换
    def parse_doors(val):
        # 处理特殊符号如">5"
        if isinstance(val, str) and '>' in val:
            return int(val.replace('>', ''))
        # 处理日期格式如"04-May"
        if isinstance(val, str) and '-' in val:
            return int(val.split('-')[0])
        # 常规数字处理
        try:
            return int(val)
        except:
            return np.nan  # 无法解析的设为缺失值
    
    df['Doors'] = df['Doors'].apply(parse_doors).astype('Int64')
    
    # 处理其他列
    df['Leather interior'] = df['Leather interior'].map({'Yes': 1, 'No': 0})
    df = df.drop(['ID'], axis=1)
    
    return df

In [55]:
# 创建组合特征
df['Age'] = 2025 - df['Prod. year']  # 车龄
df['Miles_per_year'] = df['Mileage'] / df['Age']  # 年均里程
df['Brand_Model'] = df['Manufacturer'] + '_' + df['Model'] # 品牌-车型组合特征

In [56]:
df = preprocess_data(df)

In [57]:
df.head(10)

,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags,Age,Miles_per_year,Brand_Model
0,13328,1399.0,LEXUS,RX 450,2010,Jeep,1,Hybrid,3.5,186005,6,Automatic,4x4,4,Left wheel,Silver,12,15,12400.333333,LEXUS_RX 450
1,16621,1018.0,CHEVROLET,Equinox,2011,Jeep,0,Petrol,3.0,192000,6,Tiptronic,4x4,4,Left wheel,Black,8,14,13714.285714,CHEVROLET_Equinox
2,8467,NaN,HONDA,FIT,2006,Hatchback,0,Petrol,1.3,200000,4,Variator,Front,4,Right-hand drive,Black,2,19,10526.315789,HONDA_FIT
3,3607,862.0,FORD,Escape,2011,Jeep,1,Hybrid,2.5,168966,4,Automatic,4x4,4,Left wheel,White,0,14,12069.000000,FORD_Escape
4,11726,446.0,HONDA,FIT,2014,Hatchback,1,Petrol,1.3,91901,4,Automatic,Front,4,Left wheel,Silver,4,11,8354.636364,HONDA_FIT
5,39493,891.0,HYUNDAI,Santa FE,2016,Jeep,1,Diesel,2.0,160931,4,Automatic,Front,4,Left wheel,White,4,9,17881.222222,HYUNDAI_Santa FE
6,1803,761.0,TOYOTA,Prius,2010,Hatchback,1,Hybrid,1.8,258909,4,Automatic,Front,4,Left wheel,White,12,15,17260.600000,TOYOTA_Prius
7,549,751.0,HYUNDAI,Sonata,2013,Sedan,1,Petrol,2.4,216118,4,Automatic,Front,4,Left wheel,Grey,12,12,18009.833333,HYUNDAI_Sonata
8,1098,394.0,TOYOTA,Camry,2014,Sedan,1,Hybrid,2.5,398069,4,Automatic,Front,4,Left wheel,Black,12,11,36188.090909,TOYOTA_Camry
9,26657,NaN,LEXUS,RX 350,2007,Jeep,1,Petrol,3.5,128500,6,Automatic,4x4,4,Left wheel,Silver,12,18,7138.888889,LEXUS_RX 350

In [58]:
df.describe()

,Price,Levy,Prod. year,Leather interior,Engine volume,Mileage,Cylinders,Doors,Airbags,Age,Miles_per_year
count,14681.000000,10929.000000,14681.000000,14681.00000,14681.000000,1.468100e+04,14681.000000,14681.0,14681.000000,14681.000000,1.468100e+04
mean,17729.341939,911.100741,2011.563381,0.76364,2.352762,1.097255e+06,4.634902,3.942783,6.799264,13.436619,5.404574e+04
std,17822.538641,466.112841,4.812077,0.42486,0.901162,4.133381e+07,1.232426,0.362208,4.347691,4.812077,1.881626e+06
min,1.000000,87.000000,1985.000000,0.00000,0.000000,0.000000e+00,1.000000,2.0,0.000000,5.000000,0.000000e+00
25%,5372.000000,640.000000,2010.000000,1.00000,1.800000,7.285700e+04,4.000000,4.0,4.000000,10.000000,6.307692e+03
50%,14069.000000,781.000000,2012.000000,1.00000,2.000000,1.289650e+05,4.000000,4.0,6.000000,13.000000,9.861692e+03
75%,23364.000000,1077.000000,2015.000000,1.00000,2.500000,1.930000e+05,6.000000,4.0,12.000000,15.000000,1.371429e+04
max,194438.000000,11714.000000,2020.000000,1.00000,20.000000,2.147484e+09,16.000000,5.0,16.000000,40.000000,1.263226e+08

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14681 entries, 0 to 14680
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Price             14681 non-null  int64
 1   Levy              10929 non-null  float64
 2   Manufacturer      14681 non-null  object
 3   Model             14681 non-null  object
 4   Prod. year        14681 non-null  int64
 5   Category          14681 non-null  object
 6   Leather interior  14681 non-null  int64
 7   Fuel type         14681 non-null  object
 8   Engine volume     14681 non-null  float64
 9   Mileage           14681 non-null  int64
 10  Cylinders         14681 non-null  int64
 11  Gear box type     14681 non-null  object
 12  Drive wheels      14681 non-null  object
 13  Doors             14681 non-null  Int64
 14  Wheel             14681 non-null  object
 15  Color             14681 non-null  object
 16  Airbags           14681 non-null  int64
 17  Age               14681 non-null  int64
 18  Miles_per_year    14681 non-null  float64
 19  Brand_Model       14681 non-null  object
dtypes: Int64(1), float64(3), int64(7), object(9)
memory usage: 2.3+ MB

In [60]:
df.to_csv(r"D:\GitHubRepos\is6400-business-data-analytics\data\further_cleaned_dataset.csv", encoding="utf-8-sig", index=False)